/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package camera.analyzer;

import com.mollin.yapi.exception.YeelightSocketException;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws YeelightSocketException {
        LightController lightController = new LightController();
        new LocalDataSource().registerObserver(event -> {
            switch (event.getName()) {
                case "person":
                    lightController.setPowerOn();
                    break;
                case "bottle":
                    lightController.setPowerOff();
                    break;
            }
        });
    }
}
